### ISSUE TITLE
OS error occured

### ISSUE THREAD

**Issue by sunjung27** [rasguanabana/ytfs#10]
Hi. I installed ytfs with pip3 install. However it turns out that there is some error on my computer so I cannot run the source code. 

![ytfs_error1](https://cloud.githubusercontent.com/assets/6996339/8814325/1aa83208-3046-11e5-999c-a0bbf795fde3.png)

After see this message, I just delete ytfs with pip uninstall and installed it with python setup.py install, but same error occurs. Is there any way to solve this problem?

Thanks.

**Comment by rasguanabana** [comment]
It seems like you are using Windows, which unfortunately is unsupported platform. This is because there's no FUSE implementation available for Windows (sorry for not pointing it out in readme, I'll add a note). The only solution I can think of is sharing ytfs over network from some Unix-like system.

**Comment by sunjung27** [comment]
Oh.. Yes I'm using Windows 8 (64Bit). It would be great if you add a comment on readme file :) Thank you for your help!

**Comment by rasguanabana** [comment]
Note added.

I'll also try to test YTFS with [Dokany](https://github.com/dokan-dev/dokany) on Windows. I don't expect much, but maybe it will work :)
